name: Sync Repositories Workflow
on:
  push:
    paths:
    - '.new-additions'
    - 'http/cves/2022/CVE-2022-27043.yaml'
    - 'http/cves/2023/CVE-2023-44393.yaml'
    - 'http/cves/2024/CVE-2024-39903.yaml'
    - 'http/cves/2024/CVE-2024-39907.yaml'
    - 'http/cves/2024/CVE-2024-6205.yaml'
    - 'http/cves/2024/CVE-2024-6366.yaml'
    - 'http/cves/2024/CVE-2024-6396.yaml'
    - 'http/cves/2024/CVE-2024-6922.yaml'
    - 'http/cves/2024/CVE-2024-7188.yaml'
    - 'http/misconfiguration/deployment-interface-exposed.yaml'
    - 'http/misconfiguration/installer/quickcms-installer.yaml'
    - 'http/misconfiguration/manage-cabinet-register.yaml'
    - 'http/osint/user-enumeration/substack.yaml'
    - 'http/vulnerabilities/esafenet/esafenet-netsecconfigajax-sqli.yaml'
    - 'http/vulnerabilities/esafenet/esafenet-noticeajax-sqli.yaml'
    - 'http/vulnerabilities/landray/landray-oa-replaceextend-rce.yaml'
  workflow_dispatch:
jobs:
  triggerRemoteWorkflow:
    if: github.repository == 'projectdiscovery/nuclei-templates'
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Remote Workflow with curl
      run: |
        curl -i -s -k -X 'POST' -H 'Host: api.github.com' -H "Authorization: token ${{ secrets.GTOKEN }}" --data-binary $'{\"ref\":\"main\"}' 'https://api.github.com/repos/projectdiscovery/early-templates/actions/workflows/reposync.yml/dispatches'
